---
title: "Education and Experience"
---

EDUCATION

Case Western Reserve University - 2026

BA Epidemiology Candidate

EXPERIENCE

As someone who is interested in public health, there are 2 experiences that have been pivotal in pointing me forward on this path.

This past summer, I worked as a Mayoral Fellow at the City of Detroit Health Department within the Epidemiology and Communicable Diseases divisions. My project for the Epidemiology division was to conduct informational interviews with the heads of the other divisions within the health department, do thematic analyses of the information gleaned, and develop recommendations on making partnerships with the Epidemiology division more effective. This gave me a stronger understanding of the collaboration necessary to function in public health spaces. With the Communicable Diseases division, I developed a preliminary audit tool for the Michigan Disease Surveillance System which will allow the division to better track how efficiently disease investigations are being handled. This audit tool is now being used to achieve the department's goal of national accreditation.

During the summer of 2023, I took a study abroad course through CWRU's Mandel School of Applied Social Sciences in Cape Town, South Africa. Part of this course was to job shadow with community partners. My field placement was with the Department of Social Development in Langa Township. While there, I participated in home visits, intake meetings, and case management discussions. This provided unique insight into the function of social work in post-apartheid South Africa and what it is like working in various cultural infrastructures.
